# Generated by Django 2.1.7 on 2019-04-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_product_hot_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hot_product',
            new_name='exclusive',
        ),
    ]
