# Generated by Django 2.1.7 on 2019-04-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20190416_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exclusive',
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.CharField(blank=True, max_length=255, verbose_name='тип продукта'),
        ),
    ]
