# Generated by Django 2.1.7 on 2019-04-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190417_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='type')),
                ('description', models.TextField(blank=True, verbose_name='description type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
        ),
    ]
