# Generated by Django 2.1.7 on 2019-04-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20190419_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type_product',
            new_name='type',
        ),
    ]
