# Generated by Django 2.1.7 on 2019-05-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0002_auto_20190415_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={},
        ),
    ]
